<?php
$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8');
$this->headTitle()->setSeparator(' - ');
$this->headTitle('Sistema de Progressão Docente - Unicap');
echo $this->doctype();
?>
<html>
    <head>
        <?php echo $this->headMeta(); ?>
        <?php echo $this->headTitle(); ?>
        <?php echo $this->headLink()->prependStylesheet($this->baseUrl() . '/css/site.css'); ?>

    </head>
    <body>
        <div id="bg">
            <div id="header">
                <div id="menu"><img src=" <?php echo $this->baseUrl() . '/images/logo1.png'; ?>">
                    <h1>Sistema de Progressão Docente</h1>
                </div>
            </div>

            <div id="login">
                <?php echo $this->layout()->content; ?>

            </div>
        </div>
    </body>
</html>
