
<h1>Últimos 10 Requisitos</h1>

<table>
    <tr>
        <th>Data</th>
        <th>Requisito</th>
        <th>Cód. Atividade</th>
        <th>Requerente</th>
        <th>Pontos</th>
        <th>Estado</th>
        <th>Comprovante</th>        
    </tr>
    <?php if (isset($this->requisitos)): ?>
    <?php foreach ($this->requisitos as $requisito): ?>
            <tr>
                <td><?php echo $requisito->data; ?></td>
                <td><?php echo $requisito->id; ?></td>
                <td><?php echo $requisito->atividade; ?></td>
                <td><?php echo $requisito->mat_requerente; ?></td>
                <td><?php echo $requisito->pontos; ?></td>
                <td><?php echo $requisito->estado; ?></td>
                <td><a href="<?php echo $requisito->comprovante; ?>" target="_blank">visualizar</a></td>
                
            </tr>
    <?php endforeach; ?>
    <?php else: ?>
                <h4>Não há requisitos</h4>
    <?php endif; ?>

</table>